### ISSUE TITLE
Nelze zobrazit pojmy slovníku

### ISSUE THREAD

**Issue by IR158** [opendata-mvcr/sgov-assembly-line#100]
Dobrý den,

nelze zobrazit pojmy slovníku agendy A53 k editaci v prac. prostoru Veřejné zakázky (TermIt), přestože tam jsou. Ostatní slovníky fungují, týká se pouze agendy A53. 
![Slovník A53](https://user-images.githubusercontent.com/97511616/160552331-68bcd0ca-5085-441d-bfe6-357e00555278.png)

**Comment by MichalMed** [comment]
může souviset s cachí? @blcham

**Comment by blcham** [comment]
Vypada to spis problem s triple-store, viz. : 
![image](https://user-images.githubusercontent.com/3962237/161449619-b3b77198-e08d-4321-aced-49a08180a55a.png)

Zda se zeby melo pomoct smazani tech problematickych triplu jak je napsano v message:
```
message: "Expected single value with language tag cs of attribute definition of instance <https://slovník.gov.cz/agendový/slovn-k-agendy-a53-zad-v-n-ve-ejn-ch-zak-zek/pojem/datum-a-čas-začátku-lhůty>, but got multiple."
requestUri: "/modelujeme/sluzby/termit-server/rest/vocabularies/slovn-k-agendy-a53-zad-v-n-ve-ejn-ch-zak-zek/terms/roots"
```

Tedy jednu definici bych smazal :).

**Comment by blcham** [comment]
Je tam [rozdil v mezere nakonci](https://xn--slovnk-7va.gov.cz/modelujeme/sluzby/db-server/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fagendov%C3%BD%2Fslovn-k-agendy-a53-zad-v-n-ve-ejn-ch-zak-zek%2Fpojem%2Fdatum-a-%C4%8Das-za%C4%8D%C3%A1tku-lh%C5%AFty), to ze se to podarilo ulozit dva-krat je vsak bug:
![image](https://user-images.githubusercontent.com/3962237/161449842-55141732-f26e-4bd8-aa31-c93b014a838a.png)

Jestli chces triple smazat, napis.

**Comment by MichalMed** [comment]
Jak píše výše @blcham , jednalo se o chybu v datech. Ta je opraveno a zobrazování už v TermItu funguje - tento ticket tedy zavírám. Zbývá ověřit, jak tam chyba vznikla. @IR158 Nedělali jste v poslední době úpravy definic u existujícíh pojmů?
