### ISSUE TITLE
Nejde otevřít workspace v OG

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/sgov-assembly-line#103]
# Popis problému
Ve slovnících ve WS https://xn--slovnk-7va.gov.cz/modelujeme/workspace/instance260148824 se snažím opravit rozbitý model způsobený bugem OG. Tento bug zanesl do modelu k vazbám "má-vlastnost" apod. tu samou vazbu ale v obráceném směru. To vede ke špatnému modelu. Je zřejmě nutné to opravit ručně, takže to v tomto WS zkouším, ale nejde mi to:

1) WS se mi nedaří otevřít, pokud tam mám všechny slovníky, které chci spravit. Je možné, že vadí odstranění slovníku vyhlášky 528/2006 - byla zrušena, slovník je nutno zahodit (https://github.com/opendata-mvcr/ssp/commit/d7003e84771677f42ab670e3965bbac66612bc91). Smazání slovníku ale nesmí VL vadit.
2) Nechal jsem jen slovník 329/2020. Pak se mi podařilo v OG otevřít. Udělal jsem opravy - smazal jsem špatné směry vazeb pro typy vlastností asociované s https://slovník.gov.cz/legislativní/sbírka/329/2020/pojem/etapa-životního-cyklu-isvs. WS jsem vypublikoval.
3) WS ale nyní nejde otevřít a smazané špatné směry vazeb stále v modelu jsou, nebo tam jsou nějak divně zdá se mi, např u https://slovník.gov.cz/legislativní/sbírka/329/2020/pojem/plán-ukončení-fáze jde o https://slovník.gov.cz/describe/?url=nodeID%3A%2F%2Fb5867687 a https://slovník.gov.cz/describe/?url=nodeID%3A%2F%2Fb5867689 (jsou to restrikce, které říkají že hodnotami inverze je vlastností, tj. má vlastnost, je https://slovník.gov.cz/legislativní/sbírka/329/2020/pojem/etapa-životního-cyklu-isvs)

# Závažnost problému
2. je to vážný problém,

**Comment by MichalMed** [comment]
@bindeali zkus prosím projít logy a zjisti, čím by to mohlo být. @martinnec mohl bys upřesnit, které triply tomu mohou dělat problémy? V poslední době jsme v OG fixovali nějaké bugy a omezili tím počet některých typů vztahů, které mohou vést z/do objektů. Je možné, že to vzniklo tím a zároveň by to ale zabraňovalo tomu, aby stejné chyby znovu vznikly.

**Comment by MichalMed** [comment]
@martinnec https://xn--slovnk-7va.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance43022884 mě připadá, že to funguje. Mohl bys zkusit ověřit, nejsem si jistý, co přesně způsobovalo tu chybu a netroufám si jí replikovat.

**Comment by martinnec** [comment]
Tak už ok.
