### ISSUE TITLE
Model vytvořený v ontographeru nemá v TermItu žádnou hierarchii

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#11]
Je to vidět na příkladě eSbírky. eSbírka je komplexní model vytvořený v OntoGrapheru, obsahuje semantické vazby mezi pojmy, včetně podtříd, vlastností atd. Když ho nahraju do TermIta, mám glosář bez jakýchkoliv vztahů mezi pojmy. Očekával bych minimálně:
- hierarchie pojmů podle generalizací narrower/broader,
- related terms, kromě výše zmíněných vlastnosti, vztahy.

**Comment by MichalMed** [comment]
Nemigrují se ani importované slovníky, ačkolvi v modelu importované jednoznačně jsou.

**Comment by psiotwo** [comment]
@MichalMed prosím otestuj na dev

**Comment by MichalMed** [comment]
@psiotwo https://slovník-test.mvcr.gov.cz/modelujeme/ nezobrazuje žádné workspacy, ani mi neumožní žádný vytvořit (logged in as avo@kado.es)

**Comment by psiotwo** [comment]
@MichalMed tohle by mělo být dle komentářů ke zkontrolování.
