### ISSUE TITLE
Neuložil se diagram

### ISSUE THREAD

**Issue by IR158** [opendata-mvcr/sgov-assembly-line#114]
Dobrý den,
Ontographer - Pracovní prostor Veřejné zakázky
Pracovali jsme s diagramem Subjekty, po hodině práce diagram vypadal jako na screenu 1
![Screen 1](https://user-images.githubusercontent.com/97511616/170497904-7e03b644-0bc8-4551-984d-395f159452c5.png)
.
Poté jsme aktualizovali stránku v prohlížeči a chvíli nešlo pracovní prostor načíst. Jakmile se to podařilo, diagram se vrátil do původního stavu, tzn. neuložily se žádné změny, viz screen 2
![Screen 2](https://user-images.githubusercontent.com/97511616/170498419-7de2668b-c1b3-4e92-93f3-8af22c6c0a21.png)
:

Poradili byste nám, zda neděláme něco špatně? Měli jsme za to, že se diagram průběžně ukládá.

**Comment by MichalMed** [comment]
@bindeali prosím, podívej se na to. Nejedná se o stejný problém jako jsem reportoval včera?

**Comment by bindeali** [comment]
@MichalMed V nynější verzi se mi to nedaří zreprodukovat, diagram Subjekty tam vidím a mnou vytvořený diagram nemizí:
![image](https://user-images.githubusercontent.com/56399637/171571492-75d58845-85b5-48ec-93e3-d3f9f30fd649.png)
