### ISSUE TITLE
Mizející definice

### ISSUE THREAD

**Issue by IR158** [opendata-mvcr/sgov-assembly-line#117]
TermIT - Veřejné zakázky
Do slovníku agendy A53 byly vloženy definice, pojmy uloženy. Nicméně po následné kontrole definice u některých pojmů opětovně mizí, např. Zadává zadávací postup, Je zadavatelem, Je dodavatelem, Je účastníkem atd. Přikládám některé příklady obrázků s uloženými definicemi (nyní se ve slovníku už nezobrazují).
![mizející definice 4](https://user-images.githubusercontent.com/97511616/171841863-456ab202-4ee5-4ca1-892d-e5cbd2202490.png)
![Snímek obrazovky 2022-06-03 122041 mizející definice](https://user-images.githubusercontent.com/97511616/171841915-9ece8e15-2c24-45e9-8765-f0a082ec082b.png)

**Comment by MichalMed** [comment]
Zkoušel jsem zreprodukovat, ale nepovedlo se mi to. Nejprve jsem k pojmu vyplnil definice v systému TermIt a podíval jsem se do databáze. Tam nejprve nebyly, ale v systému OntoGrapher jsem je viděl. Cca po pěti minutách se objevily i v databázi. Počítám, že chvilku trvá, než se do databáze propíšou. Zkuste prosím zreprodukovat problém a pokud vám definice zmizí znovu, dejte mi vědět s popisem přesných pojmů (ideálně odkazem na IRI) a textu definice. Díky.
