### ISSUE TITLE
Chyba 404

### ISSUE THREAD

**Issue by londoss** [opendata-mvcr/sgov-assembly-line#120]
Pokud je to možné, pokuste se informaci o chybě rozepsat dle následující struktury, pomůžete nám ji rychleji identifikovat a opravit.

# Popis problému
Při výběru pracovního prostoru se zobrazí chyba 404

# Závažnost problému
Nemožnost dále pracovat

# Alternativy řešení
-
![Výstřižek](https://user-images.githubusercontent.com/13707503/185597558-65ae2934-206e-4cd8-bc4a-40625825142a.PNG)

**Comment by londoss** [comment]
Ještě doplním, že problém je u všech pracovních prostorů přiřazených ke mě stejný.
Ostatní prostory se mi zobrazí.

**Comment by MichalMed** [comment]
Problém nastal z toho důvodu, že v současné verzi pracovní linky musí být každý pracovní prostor v samostatném kontextu. V ptraxi to znamená, že všechny pracovní soubory musí být nahrány v samostaném souboru. Testoval jsem to zatím na jednom slovníku a sice na https://slovník.gov.cz/modelujeme/workspace/itil-v3---slovn%C3%AD%C4%8Dek-term%C3%ADn%C5%AF-definic-a-zkratek-itsmf-czech-republic-os. Prosím o ověření, že je všechno v pořádku a případné nahraju zbývajících 18 pracovních prostorů.

**Comment by londoss** [comment]
Dobrý den. Prostor ITIL takto funguje, dostanu se na něj i pojmy.
