### ISSUE TITLE
Nenačtení pracovních prostorů

### ISSUE THREAD

**Issue by londoss** [opendata-mvcr/sgov-assembly-line#121]
Pokud je to možné, pokuste se informaci o chybě rozepsat dle následující struktury, pomůžete nám ji rychleji identifikovat a opravit.

# Popis problému
Po přihlášení se nenačtou pracovní prostory. Nezobrazí se žádná chyba.

# Závažnost problému
Není možné pracovat 

# Alternativy řešení
/
![screen](https://user-images.githubusercontent.com/13707503/185597979-d978de42-b6ff-4477-9329-a42f56ff6e10.png)

**Comment by MichalMed** [comment]
nejsem schopen zreprodukovat
