### ISSUE TITLE
Publikace slovníku failuje, ale slovník se publikuje

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#126]
V okamžiku, kdy v mission control spustím publikaci, trvá hrozně dlouho a nakonec zfailuje (červená hláška). Ale při pohledu na SSP jsou data publikována. Publikace je asi v pořádku, ale pravděpodobně vyhodí nějaký minor error, který vede k chybové hlášce. Bylo by dobré se na to podívat.

# Užitečnost
zatím nemá vysokou prioritu, ta ale přijde se změnou mission controlu

**Comment by Mighantos** [comment]
Co se týče rychlosti tak z procesu publikace mi na lokálu 88% času zabírá práce s gitem (převážně vytváření commitů) a jen 2% času trvá vytvoření finální podoby dokumentů. To je rozhodně zvláštní.

**Comment by MichalMed** [comment]
jsi schopen to nějak zreprodukovat s nginxem, nebo to joe na tebe moc?

**Comment by Mighantos** [comment]
Zreprodukoval jsem to s nginxem na lokálu a hází mi to taky 504.

**Comment by Mighantos** [comment]
Vytvořil jsem ticket v sgovu o tom že je potřeba to zrychlit.

**Comment by blcham** [comment]
@MichalMed zmenil jsem navic nastaveni proxy pro DEV i PROD instanci, takze po update Michalovho kodu budu fungovat oboje instance.

Na PROD-ukci jsem to navic nasadil a funguje:
![image](https://user-images.githubusercontent.com/3962237/201065726-88e7680e-e98e-41f9-ac7f-c64b7ffea93d.png)
