### ISSUE TITLE
Nelze smazat slovník z pracovního prostoru

### ISSUE THREAD

**Issue by bindeali** [opendata-mvcr/sgov-assembly-line#134]
# Popis problému
V Kontrolním panelu testovacího prostředí u [mého pracovního prostoru
](https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/workspace/instance-93306467) nelze smazat slovník - dostanu chybu "Nepodařilo se smazat slovník". Výstup z konzole:
![image](https://user-images.githubusercontent.com/56399637/217334964-10ac27d2-540c-482a-88a2-ce2019865b1c.png)

# Závažnost problému
4. příliš mojí práci neovlivňuje.

**Comment by MichalMed** [comment]
Já ho normálně smazal.
