### ISSUE TITLE
V OG nelze vložit název pojmu ze schránky

### ISSUE THREAD

**Issue by trusinas** [opendata-mvcr/sgov-assembly-line#136]
# Popis problému
Pokud uživatel vytváří nový pojem v OG kliknutím na plátno a pojem vloží ze schránky, nelze pojem uložit. Tlačítko Uložit není aktivní.

# Závažnost problému
Uvedený problém zpomaluje práci s OG. Workaround je v pojmu něco dopsat nebo smazat - poté je tlačítko Uložit aktivní.

**Comment by MichalMed** [comment]
Neumím zreplikovat (Firefox @ Ubuntu 22.04), ale od zadání issue byla nasazena nová verze. Zkuste zreplikovat. a pokud problém přetrvává, tak znovuotevřete issue.
