### ISSUE TITLE
Změna názvu pojmu

### ISSUE THREAD

**Issue by Zuwor** [opendata-mvcr/sgov-assembly-line#137]
Pokud je to možné, pokuste se formulovat svůj návrh dle následující struktury, pomůžete nám jej efektivněji zpracovat.

# Popis
Navrhujeme do aplikace implementovat možnost provádět změnu názvu pojmů. 

# Využití
Přinese-li zákonná norma změnu pojmu, je třeba mít možnost pojem upravit. 
Při zpracování glosáře či konceptuálního modelu může dojít k překlepu, který je třeba následně opravit. 

# Užitečnost
Popište, jak užitečná Vám funkce přijde
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by MichalMed** [comment]
Výrobní linka podporuje jak změnu názvu pojmu, tak vytváření alternativnách labelů, které se budou zobrazovat pro různé usecasy. Změna názvu se dá udělat v aplikaci TermIt (dostanete se do ní tlačítkem editovat pojmy v kontrolním panelu) v editaci detailu pojmu:
![image](https://user-images.githubusercontent.com/3779672/225613850-ad61f1d7-d1bb-4c66-92d3-295bdf713854.png)
Alternativní labely se dají vytvářet v aplikaci OntoGrapher (tlačítko editovat vztahy v kontrolním panelu). Po kliknutí na pojem v pravém sloupci můžete přidávat alternativní labely (synonyma):
![image](https://user-images.githubusercontent.com/3779672/225614323-94c0113a-5721-476e-80d2-972b459d3f03.png)
Kliknutím na ikonu štítku vyberete název, který se bude zobrazovat v aplikaci.

V praxi by ale mělo platit to, že pokud legislativa změní pojem natolik, že stávající pojem už významově neodpovídá, je potřeba vytvořit nový pojem (pravděpodobně celou novou verzi slovníku).
