### ISSUE TITLE
Zobrazování slovníků

### ISSUE THREAD

**Issue by Zuwor** [opendata-mvcr/sgov-assembly-line#138]
# Popis
Doplnit funkci pro zobrazení slovníku. 

# Využití
Potřebuji-li se pouze podívat do slovníku, není to možné. Musím k tomu použít funkci pro jeho editaci. Ke slovníku se pak uloží informace o tom, že jsem se podílela na jeho změně. Žádnou změnu jsem do slovníku přitom neudělala. 

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by MichalMed** [comment]
K nahlížení do slovníků, které jsou již publikované, slouží aplikace ShowIt (https://slovník.gov.cz/prohlížíme). Pokud se chcete dívat na navrhované změny, ke kterým dochází ve výrobní lince, musíte k tomu použít aplikace TermIt nebo ShowIt. Pokud žádné změny neuděláte, tak se nikam nezapíše, že jste se podílela na editaci.

Mohla byste případně ukázat, jak se problém konkrétně projevuje pomocí popisu úkonnů nutných k jeho replikaci, případně screenshoty? Díky

**Comment by Zuwor** [comment]
Dobrý den. Ráda bych doplnila printscreen, ale nemohu se dnes celý den dostat do testovací verze výrobní linky. Jde o to, že v seznamu slovníků je vedle daného slovníku tlačítko pro editaci slovníku, ale chybí tlačítko pro prosté zobrazení slovníku. 
Použila jsem tedy tlačítko pro editaci. Po opuštění slovníku se mi zobrazila informace, že jsem ve slovníku provedla změny, přestože jsem žádné neprovedla.

**Comment by MichalMed** [comment]
Aha, asi chápu. Jak jsem psal výše, cílem výrobní linky není zobrazování slovníků, ale jejich editace. K zobrazování slouží aplikace showit. 
V okamžiku, kdy začnete nějaký slovník editovat, tak se v kontrolním panelu výrobní linky vytvoří projekt s kopií tohoto slovníku. Ten se potom zobrazuje v záložce projekty. I bez toho, abyste dělali v kopii nějaké změny. Autor a datum editace je v tomto púřípadě spojeno s vytvořením projektu.
Pokud vám tyto koncepty nejsou jadné, doporučuji vám účast na školení příští týden: https://docs.google.com/forms/d/e/1FAIpQLSdYaqGBsnr-kyxM5pubiZjqnbUO8qcXO0S60BscCanwJTM4GQ/viewform

**Comment by MichalMed** [comment]
Ano, ze školení se pravidelůně pořizují záznamy, které jsou na vyžádání předávány účastníkům.
