### ISSUE TITLE
VL Demo neobsahuje všechny pracovní prostory

### ISSUE THREAD

**Issue by trusinas** [opendata-mvcr/sgov-assembly-line#139]
# Popis problému
DEMO VL (https://onto.fel.cvut.cz/modelujeme/) na záložce Otevřené úpravy neobsahuje všechny pracovní prostory, které zde byly před aktualizací.
Bylo by možné obnovit některé pracovní prostory?
Jdo o pracovní prostory, které vytvořil:
Šimon Trusina
Dominika Andraščíková

# Závažnost problému
2. je to vážný problém (modely je nutné znovu vytvořit)

**Comment by MichalMed** [comment]
Demo není určené k modelování, ale k seznámení s nástroji VL pro začátečníky, případně pro ukázky na školení. Modely vytvořené v demu není možné publikovat v SSP. Během aktualizace demo instance je databáze promazávána. Máme uložené některé zálohy a modely je tedy možné v rámci demo instance obnovit, ale ani tak je nebude možné publikovat. Pokud chcete modely publikovat do SSP, je potřeba je modelovat v produkční verzi systému. Jestli chcete obnovit slovníky v demu, dejte mi vědět, o jaké slovníky se jedná. Jsou to tyto:
https://github.com/kbss-cvut/ssp/pull/7
https://github.com/kbss-cvut/ssp/pull/25 ?

**Comment by trusinas** [comment]
Rozumím. Modely nebyly určené k publikaci, ale k "pedagogické činnosti", proto nebyly vytvářeny na produkční verzi.
Poprosím o obnovu:
https://github.com/kbss-cvut/ssp/pull/7
https://github.com/kbss-cvut/ssp/pull/21
https://github.com/kbss-cvut/ssp/pull/25

Díky!

**Comment by MichalMed** [comment]
@blcham Miro mohl bys obnovit požadované slovníky? Díky

**Comment by blcham** [comment]
Hotovo, vytvoril jsem 3 projekty jak je videt na obrazku:

![image](https://user-images.githubusercontent.com/3962237/225645892-b55a24ea-1e61-4f38-96d6-fcefa4a581ce.png)

**Comment by trusinas** [comment]
Můžu poprosit o kontrolu u https://onto.fel.cvut.cz/modelujeme/projects/instance1959727157? Projekt je prázdný:
![image](https://user-images.githubusercontent.com/42774229/225691468-b11ee15f-887c-480a-a2a2-8bc7ccff6ff1.png)
