### ISSUE TITLE
V canvasu 1 se objevují pojmy z canvasu 2

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#27]
# Popis problému
V pracovním prostoru Slovník vyhlášky č. 393/2020 Sb., o digitální technické mapě kraje v záložce Předmět úpravy se objevují pojmy, které do ní nebyly přidány, ale byly vytvořeny v záložkách Obsah digitální technické mapy a § 2 (1). Můžu je skrýt, ale potom, co se vrátím do záložky Předmět úpravy se mi znovu objeví.

# Závažnost problému
4. příliš mojí práci neovlivňuje. ALE JE TO OTRAVNÉ

**Comment by bindeali** [comment]
@MichalMed až budeš mít čas, můžeš to vyzkoušet na `slovník-test` a kdyžtak zavřít?

**Comment by MichalMed** [comment]
Ahoj, na slovník-test se to dá zkoušet blbě, protože nemůžu chybu zreprodukovat tam, kde jsem ji objevil. Když jsem se jí "pokusil" zreprodukovat na testu, tak se to nepovedlo, ale co já vím, čím to bylo způsobeno. Zavírám a otestuju to na produkci až to nasadíš.
