### ISSUE TITLE
Nelze otevřít workspace pro "EDITOVAT POJMY"

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/sgov-assembly-line#29]
# Popis problému
- nelze otevřít workspace pro editaci pojmů
- kontrolní panel, tlačítko "EDITOVAT POJMY"
- https://slovník.gov.cz/modelujeme/workspace/instance-1993851850 (ale zkoušel jsem i řadu dalších)
- před tím jsem smazal všechny svoje workspaces
- v OntoGrapheru otevřít workspace lze

# Závažnost problému
2. je to vážný problém,

**Comment by karelklima** [comment]
@martinnec Asi to byl nějaký krátkodobý výpadek, teď jsem to testoval a zdá se, že to funguje, jak má.

**Comment by psiotwo** [comment]
@martinnec @karelklima podle mě vyřešeno/nereprodukovatelné. Navrhuji zavřít. Souhlasíte?

**Comment by martinnec** [comment]
Souhlas

**Comment by karelklima** [comment]
Souhlas, zavírám.
