### ISSUE TITLE
Podpora sdílení a správu diagramů

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/sgov-assembly-line#33]
# Popis
V současné době jsou diagramy ukládány pouze v pracovním prostoru a nejsou publikovány. Uživatelé tak pracovní prostory raději nemažou protože mají v diagramech práci, o kterou nechtějí přijít. Tím je porušena původní myšlenka pracovních prostorů, jako krátkých transakcí nad SSP.

# Návrh implementace

**OntoGrapher**: 
OntoGrapher bude načítat všechny diagramy z SSP Cache pro daný slovník z WS. Taky umožní ke slovníku přidávat diagram (jak teď vybrat slovník? (nový popup třeba) - v budoucnu by měl být 1 slovník per workspace tak by to neměl být problém) a všechny diagramy daného slovníku měnit - název i obsah.  OntoGrapher zajistí, aby nebylo možné vytvořit diagram s názvem, který již v daném slovníku existuje. Diagramy daného slovníku bude možné upravovat a mazat. 

v budoucnu: zvážit možnost kopírovat diagramy jiných slovníků do aktuálního slovníku

**sgov-server + pipeline na GH**: 
Diagramy se budou ukládat  jako součást slovníků na GitHub. Co soubor to diagram. Každý diagram má svůj identifikátor (IRI), jehož localName bude názvem souboru (nějaký hash). Název diagramu bude pouze v datech samotných. Po zamergování workspace se musí aktualizovat SSP Cache i o diagramy.

**Comment by bindeali** [comment]
To zní jako rozumný návrh, jediné, co mě k tomu okamžitě napadá, je kolik, realisticky, bude mít každý slovník v praxi diagramů. Dokážu si jednoduše představit, že kvůli např. opuštěným diagramům nebo diagramům vztahujících se na populární slovníky bude dříve nebo později potřeba nějaký jednoduchý management/filtering diagramů v OG nebo jinde - něco ve stylu kontrolního panelu.

**Comment by psiotwo** [comment]
> To zní jako rozumný návrh, jediné, co mě k tomu okamžitě napadá, je kolik, realisticky, bude mít každý slovník v praxi diagramů. Dokážu si jednoduše představit, že kvůli např. opuštěným diagramům nebo diagramům vztahujících se na populární slovníky bude dříve nebo později potřeba nějaký jednoduchý management/filtering diagramů v OG nebo jinde - něco ve stylu kontrolního panelu.

Diagram by byl vždy připojen ke slovníku - jak by se mohl stát opuštěným (už teď je mi ho líto :-) ) ?

**Comment by psiotwo** [comment]
Domluvili jsme se, že:
- OntoGrapher změní resolution diagramového kontextu z workspace tak, že přidá do metadatového kontextu ke každému writeable slovníkového kontextu link https://slovník.gov.cz/datový/pracovní-prostor/pojem/má-diagramový-kontext. 
- SGoV server rozšíří publikaci i o diagramové kontexty připojené ke slovníkovému kontextu.

**Comment by psiotwo** [comment]
Implementováno v Milestone 1a - release 2022-01-03.
