### ISSUE TITLE
Posouvání ve schématu

### ISSUE THREAD

**Issue by Du-Baj** [opendata-mvcr/sgov-assembly-line#39]
V prohlížeč Safari na macOS se nelze posouvat ve schématu, je nutno odzoomovat a pak se zkusit přizoomovat na potřebné místo.

**Comment by MichalMed** [comment]
Pokud to chápu správně, jedná se o nástroj OntoGrapher?  Zkoušeli jste to i v jiném prohlížeči?

**Comment by MichalMed** [comment]
na macu otestuje @karelklima

**Comment by MichalMed** [comment]
Zkoušel jsem na linuxu bez myši a je to dost peklo. VIdím dvě možnosti řešení:Jako jedinné řešené vidím změnit ovládání tak, aby se plátno posouvalo pravým tlačítkem

**Comment by karelklima** [comment]
Michale, souhlas, musí to být intuitivní.

Co tohle?
- Pravým tlačítkem se bude dělat selekce (nyní je to přidání pojmu na klik)
- Klik levým tlačítkem na canvas přidá pojem
- Klik a drag levým tlačítkem na element posouvá element
- Klik a drag levým tlačítkem na canvas posouvá canvas

**Comment by Du-Baj** [comment]
Za sebe bych raději přidávání řešil pravým tlačítkem ... v navrženém výše
by mohlo docházet k tomu, že chci posouvat a místo toho vytvořím nový
pojem. Tj. jen návrh, ale přišlo by mi vhodné:

   - Levý klik - selekce
   - Levý klik a drag - posun
   - Pravý klik (a třeba volba z menu do budoucna až bude víc voleb) -
   přidání (případně kontextové menu a přidání)

Myslím, že takto by se to chovalo jako většina aplikací a bylo to
intuitivní.

Hezký den

DB
