### ISSUE TITLE
Ujistit se, že všechny nástroje výrobní linky umí pracovat s TLSv1.3

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/sgov-assembly-line#4]
# Popis
Všechny nástroje výrobní linky pracující přes HTTPS musí umět TLSv1.3

# Využití
Při každé interakci s endpointem.
Nyní je většina MV ČR serverů nastavena na podporu TLSv1.2 a TLSv1.3. TLSv1.2 již ale není doporučené pro moderní webové servery a tedy bude v nějaké (více či méně blízké) budoucnosti vypnuto, a zůstane TLSv1.3. To může způsobit problém s připojením přes HTTPS u nástrojů, které TLSv1.3 neumí, jak se to již v minulosti stalo. Dnes používané knihovny (např. Java) ale již TLSv1.3 podporují. Je tak třeba se jen ujistit, že ve výrobní lince nejsou používány staré verze, případně je updatovat.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by psiotwo** [comment]
Špatně jsem pochopil - OK, dává smysl.

**Comment by psiotwo** [comment]
- OFN form manager - upgrade to Java 11
- TermIt, SGoV - melo by byt rozbehnutelne na Java 11

**Comment by psiotwo** [comment]
Komponenty jsou aktualizovane.
