### ISSUE TITLE
Zalamování textu

### ISSUE THREAD

**Issue by Du-Baj** [opendata-mvcr/sgov-assembly-line#40]
Ikona prvku se zvětší tak, aby obsáhl celý pojem v jednom řádku ... s ohledem na to, že se často musí držet dlouhé pojmy dané legislativou je to trochu nepraktické. Pokud by se text zalamoval a případný delší název byl zkrácen a zobrazoval se v plném znění jen např. při najetí kurzoru, tak by to bylo asi přehlednější.

**Comment by MichalMed** [comment]
Omlouvám se, ale úplně nerozumím problému. Mohli byste přiblížit, v jakém nástroji je problém a krok po kroku jak konkrétně k chybě dojdete? Systém je tak komplexní, že podle popisu nedokážu určit, co se vlastně přesně děje.

**Comment by Du-Baj** [comment]
Aha, díky. Začneme více využívat. DB
