### ISSUE TITLE
Import modelu

### ISSUE THREAD

**Issue by Du-Baj** [opendata-mvcr/sgov-assembly-line#41]
Pokud by bylo možné importovat model ve standardní notaci zpracovaný běžným nástrojem (např. Enterprise Architect), tak by to umožnilo snáze překlenout počáteční fázi. Model bychom při vytváření udělali vedle a sem jej jen přemístili. Při tvorbě děláme mnoho změn (model tvoříme v kolektivu cca 10 lidí) a omezení nástroje dost ztěžují plynulost procesu.

**Comment by MichalMed** [comment]
Prosím, pošlete mi ten OWL, který vám to vrací z EA.

**Comment by MichalMed** [comment]
Po třech měsících jsem žádný vstup nedostal, takže zavírám.
