### ISSUE TITLE
Označení definice pojmu selže

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#44]
# Popis problému
V dokumentu zákona č. 56/2001 v pracovním prostoru Školení - řidiči a vozidla v testovacím nasazení výrobní linky, při označení části textu na obrázku, výběr označení definice pojmu a výběr pojmu silniční vozidlo. Potvrzení změny definice tlačítkem "Uložit". Chvilku se TermIt tváří, že pracuje, pak text zmodrá, ale popup okno zůstane. Po zavření výskyt definice zmizí (i zmodrání).

![Screenshot from 2021-10-13 14-48-05](https://user-images.githubusercontent.com/3779672/137135518-ae9163da-1c08-4001-aa71-3020b13b729a.png)

Log: 
{"message":"Expected single value with language tag cs of attribute definition of instance <https://slovník.gov.cz/legislativní/sbírka/56/2001/pojem/silniční-vozidlo>, but got multiple.","requestUri":"/modelujeme/sluzby/termit-server/rest/vocabularies/2001/terms/silni%C4%8Dn%C3%AD-vozidlo"}

# Závažnost problému
- popište, jak závažný pro práci s výrobní linkou pro Vás problém je:
2. je to vážný problém,

**Comment by psiotwo** [comment]
V datech je definice ještě třetí "Motorové nebo nemotorové vozidlo , které je vyrobené za účelem provozu na pozemních komunikacích pro přepravu osob, zvířat nebo věcí."@cs - nevím jak tam vznikla. O té něco víš?

**Comment by psiotwo** [comment]
Symptom v datech odstraněn, ale zatím jsem neřešil, proč to vzniká.

**Comment by MichalMed** [comment]
Jestli to má víc definic, tak asi formulář (na obrázku) definici napoprvé nezmění, ale přidá další.  Chtělo by to ověřit, případně opravit. Zkoušel jsem prostým přidáváním definic zreplikovat, ale asi nic.

**Comment by MichalMed** [comment]
Zatím se mi nepodařilo zreprodukovat, zavírám.
