### ISSUE TITLE
Při označení textu v anotátoru je označen celý řádek

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#50]
# Popis problému
Pokud chci vytvořit nový výskyt pojmu označením části textu, po stisknutí "mark term occurrence" se zvýrazní celý řádek. Toto zjednodušení bylo zavedeno pro definice, aby nebyl problém s vnořenými tagy, ale pro výskyty pojmu se používat nemá.

![Screenshot from 2021-11-01 21-48-29](https://user-images.githubusercontent.com/3779672/139740086-960af9b6-5b1b-4e45-b63c-a696b4806033.png)
Na obrázku jsem označil text "historickým vozidlem" a výsledkem je označení celého (posledního) řádku.

# Závažnost problému
2. je to vážný problém,

**Comment by karelklima** [comment]
Nemůžu zreprodukovat, TermIt mi vždy označí jenom to, co chci (zaokrouhleno na celá slova). Win / Chrome.

**Comment by MichalMed** [comment]
Dokonce je to zreprodukovaný ve videu https://drive.google.com/file/d/1BZS1X3jJ1qPoZUcWCA2p0_xn_MtxO3CS/view?usp=sharing

**Comment by MichalMed** [comment]
Pořád aktuální, ale nevím, koho na to po Petrově odchodu přiřadit. @blcham ?

**Comment by blcham** [comment]
To myslis cas 13:13 ?

**Comment by MichalMed** [comment]
> 

Ano. Teď jsem to znovu testoval a je to pořád chyba.

**Comment by blcham** [comment]
proberem to na meetingu

**Comment by FilipKopecky** [comment]
Problém se zdá být v anotátoru. Po spuštění textové analýzy textu, anotátor odstraní mezeru mezi číslem odstavce a samotným zněním. Potom když se snažíme použít anotaci slova které je "přilepeno" na číslo v závorce dojde k označení celého paragrafu.

Ukázka části odstavce kde dojde k useknutí mezery:

Stav před: `<var>(1)</var> Tento zákon zapracovává příslušné předpisy Evropské unie`

Stav po: `<var>(1)</var>Tento <span about="_:156c-35" property="ddo:je-výskytem-termu" content="zákon" typeof="ddo:výskyt-termu" score="1.0">zákon</span> zapracovává příslušné `

Takže jsou z toho vlastně dvě issues:

1. Označování textu obsahující mezeru a `<var></var>` na začátku řádku způsobí označení celého řádku/odstavce
2. Automatická analýza textu maže mezeru mezi `<var></var>` a textem který ji tam původně měl. 

Do opravy označovaní (problém č.1) se můžu pustit hned. Anotátor bude asi předmětem diskuse
