### ISSUE TITLE
Nefunguje přepínání jazykových verzí UI v OntoGrapheru

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/sgov-assembly-line#52]
![image](https://user-images.githubusercontent.com/718827/139855345-514d7a56-0f76-476f-9dc9-e19f5bbbd514.png)
![image](https://user-images.githubusercontent.com/718827/139855391-54e81e99-4e71-4e05-be62-82d4b493fe28.png)

**Comment by jakubklimek** [comment]
Zřejmě duplicita s https://github.com/opendata-mvcr/ontoGrapher/issues/331

**Comment by psiotwo** [comment]
@jakubklimek ten ticket je trochu vágní ... Vadí ti, že 1) vidíš "blank", nebo 2) že se při přepnutí do angličtiny nepřepne jazyk UI? 3) Nebo něco jiného?

Zavírám s vírou, že se jedná o 2) a tedy o duplicitu ^ .
