### ISSUE TITLE
Nejde dohledat druhy argument relatoru v sekci Links

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/sgov-assembly-line#57]
Nejde dohledat druhy argument relatoru v sekci "Links" pro entitu [ma-cenu](https://xn--slovnk-7va.gov.cz/generick%C3%BD/vstupn%C3%A9/pojem/m%C3%A1-cenu).

# Popis problému

- nastroj: OntoGrapher
- pracovni prostor [Test FK](https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1489397890), diagram "MB ..."
- Na screencaste je videt: 
   - hlavni problem - nejprve v sekci "Links" entitu "Částka" vubec nemohu najit, no po pridani teto entity manualne se v sekci Links objevi
   - vedlejsi problem -- musel jsem to z leveho panela tahat na dva-krat
   
https://user-images.githubusercontent.com/3962237/141316433-dfb57771-d4f2-4d7a-9272-811f532cb367.mp4

# Závažnost problému
- zpomaluje mě to,

**Comment by MichalMed** [comment]
@blcham mohl bys prosím zkontrolovat, případně zavřít?

**Comment by MichalMed** [comment]
opraveno
