### ISSUE TITLE
Nekonzistentni model pro termin ma kapacitu

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/sgov-assembly-line#59]
Pokud je to možné, pokuste se informaci o chybě rozepsat dle následující struktury, pomůžete nám ji rychleji identifikovat a opravit.

# Popis problému
- model terminu ma-kapacitu neni konzistentni s UFO (je to typ-vlastnosti a zaroven typ-vztahu)
- pracovní prostor:  [turisticky cil](https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1044794056)

![kapacita_509534051675524364](https://user-images.githubusercontent.com/3962237/141531774-9740de7c-1b24-45ad-b25a-bc326ae0b319.png)

# Závažnost problému
- zavazny

# Alternativy řešení
- zrejme by se mel odstranit typ-vlastnosti
- BTW, bohuzel ani ta cast modelu ohledne mnozstvi neni nic moc (asi by vsude u mnozstvi, hodnota, i ma jednotku meli byt kardinality 1 aby to alespon trochu davalo zmysel)

**Comment by MichalMed** [comment]
Miro, já nejsem autorem slovníku ani zmíněného pojmu. Asi bysme měli vymyslet nějaký workflow, jak řešit tyto nekonzistence. Jestli přes GH assignout autora slovníku, nebo to jen upravit. Problém je, že nevíme, kde všude je pojem použit a jak.

**Comment by MichalMed** [comment]
Při pohledu do dat v SSP tam typ-vlastnosti nikde není. V ontographeru jsem změnil stereotyp na typ vztahu (tos mohl udělat taky) a vypadá to, že je to +/- opraveno. Množství je dítě @jakubklimek , takže případné stížnosti by měly jít za ním, případně je upravím v modelu, až se dohodnete.

**Comment by MichalMed** [comment]
BTW Miro, tys tam dělal nějaký změny? Chtěl jsem vypublikovat tu změnu stereotypu pouze na typ-vlastnosti a je tam toho evidentně mnohem víc, než jen tohle. Jestlis tam dělal změny ty, tak prosím zreviduj tento PR: https://github.com/opendata-mvcr/ssp/pull/313

**Comment by blcham** [comment]
> Miro, já nejsem autorem slovníku ani zmíněného pojmu. Asi bysme měli vymyslet nějaký workflow, jak řešit tyto nekonzistence. Jestli přes GH assignout autora slovníku, nebo to jen upravit. 
Asignovani na Tebe je automaticke, vzdyt ja jsem navrhnoval ze Vam to klidne nareportuji jak doted pres SSP na konkretni osobu ... no chtel si to takhle. 

Jestli trvas natom, ze to chces reportovat tady ?! tak mne nenapada nic lepsiho jako: 
1) pridat navic cloveka ktereho se to tyka
2) alternativne udelat primo pull request v tom jinom projekte a referencovat ho tady

> Problém je, že nevíme, kde všude je pojem použit a jak.
Tak muzeme se podivat sem abychom zjistili kde je to pouzite:
https://xn--slovnk-7va.gov.cz/datov%C3%BD/turistick%C3%A9-c%C3%ADle/pojem/kapacita

**Comment by blcham** [comment]
> BTW Miro, tys tam dělal nějaký změny? Chtěl jsem vypublikovat tu změnu stereotypu pouze na typ-vlastnosti a je tam toho evidentně mnohem víc, než jen tohle. Jestlis tam dělal změny ty, tak prosím zreviduj tento PR: [opendata-mvcr/ssp#313](https://github.com/opendata-mvcr/ssp/pull/313)

- zadne zmeny jsem nedelal, no zbezne jsem se nato podival a pridal 1 komentar ... zbytek nechavam na autora.

**Comment by psiotwo** [comment]
@MichalMed v tomto repozitáři jsi historicky default assignee všech ticketů - myšlenka byla (a nepamatuju si, že bychom ji revidovali), že tento repozitář bude sběrný a bude existovat jeden člověk (teď ty), který ho bude mít v hlavě a bude rozhazovat na ostatní, to co je třeba. Jestli z toho cokoliv nefunguje, nebo má fungovat jinak je to IMO námět na retro.

**Comment by MichalMed** [comment]
Podle mě to platí pro všechny tickety týkající se vývoje. Tohle do toho moc nezapadá. Tady jsou nějaký špatný asi data, ale to asi není předmětem bug/feature developmentu. Ten workflow by určitě bylo dobrý probrat, ostatně jak píšu ve vlákně

**Comment by MichalMed** [comment]
Jinak já jsem na ry data kouknul, upravil a udělal PR. Ten obsahuje mnohem více změn nez kolik jsem udělal, tak budu muset někde vyšťourat kdo to byl. Btw ten typ vlastnosti NIKDE není

**Comment by MichalMed** [comment]
OG by měl mít kontrolu konzistence UFO (i OntoUML) podle pravidel daných vztaženými stereotypy. Bude to celkově docela dost pravidel, takže bych šel postupně. 

1. UFO stereotyp má každý pojem jenom jeden, přidáním nového ztrácí pojem původní. 
2. Dědičnost mezi nimi by asi měla fungovat podobně (@blcham - pokud se nepletu, tak typ objektu nemůže být generalizací typu vlastnosti apod.),
3. Dědičnosti mezi OntoUML vztahy (Kind nemůže specializovat roli atd...)
