### ISSUE TITLE
Po přidání slovníku do prázdného pracovního prostoru není možné přidat pojmy/vztahy bez obnovení stránky

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/sgov-assembly-line#60]
# Popis problému
V kontrolním panelu po vytvoření nového pracovního prostoru a vytvoření nového slovníku v něm (v mém případě datového) se "neodšediví" tlačítka pro editaci pojmů a vztahů v detailu pracovního prostoru. Musím stránku refreshnout, pak už to je OK.

**Comment by MichalMed** [comment]
Tohle by mělo být opraveno, @jakubklimek otestuj prosím
