### ISSUE TITLE
OG neumožňuje vytvářet vztahy mezi pojmy

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#63]
# Popis problému

Začal jsem testovat vytváření vztahů v kompaktním režimu. Při naznačení šipky mezi dvěma objekty mi vyskočí dialog, ve kterém vytvořím nový vztah (nebo vyberu jeden z existujících, chyba se projevuje stejně) a potvrdím jeho vytvoření. V ten okamžik se OG zakousne. V Logu mám status 500 nad https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/sluzby/db-server/repositories/assembly-line/transactions/e3bc9eb9-844b-49cd-bd23-03849bd78a73?action=UPDATE. 

Pokud přepnu zpět do full zobrazení, chyba se začne projevovat úplně stejně.

# Závažnost problému
1. nemohu vůbec pracovat,

**Comment by psiotwo** [comment]
@MichalMed 
Zkoušel jsem teď v https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1546316314 a podle mě to po opravě @bindeali funguje.
