### ISSUE TITLE
V Ontographeru zmizely z diagramů vazby a pojmy

### ISSUE THREAD

**Issue by AdelaBenesova** [opendata-mvcr/sgov-assembly-line#64]
V Ontographeru (pracovní prostor Veřejné zakázky) nám z diagramů zmizely vazby (ve slovnících jsou zachovány). V průběhu dne dokonce na diagramech nebyly zobrazené ani pojmy a diagramy byly prázdné. Nyní odpoledne už vidím na diagramech část pojmů (ne všechny), ale většina vazeb byla odstraněna. Přikládám screen:
![image](https://user-images.githubusercontent.com/39707054/144079122-4e42aa5c-863a-4cc3-a3e4-0bbfff6272ba.png)

Problém je pro nás závažný, schémata znovu nakreslíme, ale jen díky tomu, že máme zachované screeny. Děkuji.

Edit: Po opětovném přihlášení do pracovního prostoru a zobrazení si vztahů v Ontographeru už na diagramu nevidím ani většinu pojmů viz screen níže:
![image](https://user-images.githubusercontent.com/39707054/144079747-782e51d0-0e7c-4286-974c-a98d312aed03.png)
Informace na diagramech se mění v čase.

**Comment by MichalMed** [comment]
Zkontrolujte prosím znovu, dělali jsme nějaký maintenance. Mně se to teď zobrazuje správně.

**Comment by AdelaBenesova** [comment]
Dobrý den, na začátku minulého týdne problém přetrvával, ale tento se již diagramy zobrazují korektně. Děkuji.
