### ISSUE TITLE
Všechny labely pojmů ve WS jsou <blank>

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#67]
Narazil jsem na to během testování milestonu 1a

# Popis problému
Po otevření OG z WS vytvořeného minulý týden pro testování milestonu 1a jsou labely všech pojmů <blank>. V detailu pojmu je blank jako english verze, ale nejde překliknout na českou.
![og_blank](https://user-images.githubusercontent.com/3779672/146673086-fb50ddad-4519-4a53-83dc-d09d194e05c2.png)

# Závažnost problému

2. je to vážný problém,

# Alternativy řešení
Asi souvisí s přepínáním jazykových mutací OG.

**Comment by bindeali** [comment]
Asi nerozumím problému natolik, abych ho mohla reprodukovat. Pokud si otevřu OG v angličtině (a tím pádem i WS), tak tam mám `<blank>`, ale můžu si přepnout na češtinu tady:
![image](https://user-images.githubusercontent.com/56399637/147873896-e50eabfb-c6ef-46f5-a9fa-8a758b2eacd8.png)
Pokud myslíš nastavení zobrazovaného názvu 🏷, tak ten jde zvolit pouze z dostupných názvů/synonym daného jazyka (tj. pokud vidíš české názvy pojmů atd., 🏷 se ukáže pouze u českých názvů/synonym).

Mimochodem, `<blank>` názvy se dají kdykoliv přidat:
![image](https://user-images.githubusercontent.com/56399637/147874069-aa2a8ee8-ad93-4b75-ae2d-306a52eb88d4.png)
