### ISSUE TITLE
Milestone 1a - diagram se nezobrazí správně

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/sgov-assembly-line#68]
Při testování scénáře pro milestone 1a jsem narazil na tento problém:
Až do kroku 10 je všechno v pořádku. V novém WS se diagram zobrazí jinak, než jak vypadal v tm prvním (už smazaném).

![Screenshot from 2021-12-20 11-56-17](https://user-images.githubusercontent.com/3779672/146757085-39d3d8f1-1877-467b-bbec-6417d6c957c9.png)

Na diagramu chybí pojem Part of the builidng, ale jsou tam navíc tři blank pojmy ze 111/2009 (při přepnutí do full view je vidět, že na ně vedou relátory z 359/2011).

# Závažnost problému
2. je to vážný problém,

**Comment by MichalMed** [comment]
Jedná se o diagram Avokádovo test diagramů II

**Comment by psiotwo** [comment]
@bindeali Nesouvisí to s https://github.com/opendata-mvcr/ontoGrapher/issues/359 a  @MichalMed není to tedy už vyřešeno v https://github.com/opendata-mvcr/ontoGrapher/pull/361?

**Comment by MichalMed** [comment]
myslím si že ne, ale zkontrolui to

**Comment by MichalMed** [comment]
opraveno
