### ISSUE TITLE
Nelze editovat vztahy

### ISSUE THREAD

**Issue by AdelaBenesova** [opendata-mvcr/sgov-assembly-line#70]
Nedaří se načtení workspace Veřejné zakázky v Ontographeru. Workspace se stále načítá, nepomohla ani změna prohlížeče nebo odhlášení a přihlášení. Děkuji za informaci, zda se jedná o krátkodobý výpadek nebo o problém na mé straně. Děkuji.

![image](https://user-images.githubusercontent.com/39707054/148198784-08619370-4ac5-4897-90a2-8a91fc380fe7.png)

**Comment by MichalMed** [comment]
@bindeali mohla bys na to prosím kouknout, jestli na něco přijdeš? taky mi to nefunguje

**Comment by MichalMed** [comment]
vyřešeno, zkontrolujte prosím
