### ISSUE TITLE
Problém se zobrazením modelu v Ontographeru (blank)

### ISSUE THREAD

**Issue by AdelaBenesova** [opendata-mvcr/sgov-assembly-line#72]
Minulý týden jsem hlásila issue #70, pod mým účtem však stále nelze zobrazit diagramy v pracovním prostoru Veřejné zakázky (screen dole). Kolegové vidí data v pořádku, problém přetrvává u mne. Zkoušela jsem následující:
1. Přihlásit se na jiné pracovní stanici
2. Promazat mezipaměť prohlížeče
3. Vymazat cache Windows

Prosím o info, jak dále postupovat. Děkuji.

V Ontographeru vidím toto:
![image](https://user-images.githubusercontent.com/39707054/148566364-6719056b-4b11-4b9f-90ac-9af04abb52da.png)

**Comment by MichalMed** [comment]
Asi budete mít nastavenou angličtinu jako jazyk pro zobrazování pojmů. Klikněte si vlevo nahoře na View > Displayed vocabulary language > Čeština
![Screenshot from 2022-01-07 17-42-34](https://user-images.githubusercontent.com/3779672/148576723-c0a56eeb-dd2e-45c0-8e68-f399f93a0b4b.png)

**Comment by MichalMed** [comment]
dejte mi vědět, jestli to pomohlo

**Comment by AdelaBenesova** [comment]
Dobrý den,
velmi děkuji za reakci, bohužel to nepomohlo viz screen níže. Děkuji za
řešení, Benešová.
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

pá 7. 1. 2022 v 17:45 odesílatel Michal Med ***@***.***>
napsal:

**Comment by MichalMed** [comment]
Žádný screenshot nevidím. Můžete ho nahrát rovnou v githubu, tedy ne přímou odpovědí na e-mail?

**Comment by AdelaBenesova** [comment]
Přikládám screen obrazovky s přepnutým jazykem na češtinu. Stále vidím to samé. 
![image](https://user-images.githubusercontent.com/39707054/148651550-7611fef2-1a6f-43ee-9eba-002a699bbf85.png)

**Comment by MichalMed** [comment]
Přesně tak, rozhraní a slovník mají nezávislé nastavení jazyka. Aby bylo možné prohlížet si anglický slovník, ale v českém rozhraní.
