### ISSUE TITLE
Nelze pracovat s modely v Ontographeru

### ISSUE THREAD

**Issue by AdelaBenesova** [opendata-mvcr/sgov-assembly-line#74]
Opět máme problém s Ontographerem, ani kolegům se nedaří si načíst pracovní prostor Veřejné zakázky v Ontographeru.

**Comment by psiotwo** [comment]
@AdelaBenesova je to opraveno, prosím vyzkoušejte.

**Comment by MichalMed** [comment]
@AdelaBenesova dobrý den, můžete prosím potvrdit, jestli to už funguje?
