### ISSUE TITLE
Nenačítá se pracovní prostor

### ISSUE THREAD

**Issue by IR158** [opendata-mvcr/sgov-assembly-line#75]
Dobrý den,

v nástroji OntoGrapher se od včerejšího odpoledne nedaří načíst pracovní prostor Veřejné zakázky. Nástroj stále zobrazuje, že se pracovní prostor načítá, schémata lze zobrazit aspoň pro čtení, ale není možné s nimi pracovat a editovat vztahy.

I. Rosická

**Comment by MichalMed** [comment]
same as: #74

**Comment by psiotwo** [comment]
@IR158 je to opraveno, prosím vyzkoušejte.
