### ISSUE TITLE
Zefektivnění nastavování kardinalit

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/sgov-assembly-line#80]
# Popis
Vyplňování kardinalit vazeb v OntoGrapheru je zdlouhavé. Částečně lze práci usnadnit tak, že se vhodně definují defaultní kardinality, ale jednak to není jednoznačné (např. pro vlastnost chci 0..*, protože je nejobecnější, nebo 0..1, protože je nejběžnější?), jednak se stále může vyskytnout mnoho vazeb, kde defaultní kardinalita nevyhovuje.

Cílem je umožnit vybrat hrany (přímo selekcí, nebo všechny) a pro výběr změnit kardinality hromadně.

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to

**Comment by MichalMed** [comment]
@bindeali Alice, tohle by bylo případně na tebe, ale zatím to nemá moc velikou prioritu. DOkázala bys nějak odhadnout časovou náročnost?

**Comment by MichalMed** [comment]
1. Potřebujeme navrhnout, jak by měla vypadat default kardinalita, 
2. případně změnit si někde v "nastavení" kardinality a ty pak aplikovat pro všechny nově vytvořené vztahy. 
3. určitě aplikovat hromadné změny kardinality pro více označených hran
