### ISSUE TITLE
Problém s kompatibilitou vazeb

### ISSUE THREAD

**Issue by IR158** [opendata-mvcr/sgov-assembly-line#82]
Dobrý den,

v Ontographeru, v pracovním prostoru Veřejné zakázky mezi typem objektu a typem vztahu, stejně tak mezi typem objektu a typem vlastnosti, lze jako kompatibilní vazbu vytvořit pouze generalizaci, ostatní vazby jsou nekompatibilní. Při zobrazení v kompaktním modu potom některé objekty "plavou", viz obr. 

![Obr_1](https://user-images.githubusercontent.com/97511616/150283187-274232a3-a3fe-4776-98f5-165eaf04a2a8.png)

I. Rosická

**Comment by MichalMed** [comment]
@IR158 zkontroluje prosím funkčnost
