### ISSUE TITLE
Přidat slovník > Slovník se zobrazuje jako "undefined"

### ISSUE THREAD

**Issue by xzbozink** [opendata-mvcr/sgov-assembly-line#83]
# Kroky
1. Otevřít detail pracovního prostoru: Hlasování zastupitelstva obce
     https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/workspace/instance-809875291
2. Přidat slovník

# Výsledek
Název slovníku se zobrazuje jako "undefined".

# Očekávaný výsledek
Slovník je korektně přidán do pracovního prostoru.

# Další poznámky
TermIt zobrazuje název slovníku také jako undefined a neobsahuje žádné pojmy.
V OntoGrapheru slovník také nezobrazuje žádné pojmy.

# Závažnost problému
1. nemohu vůbec pracovat

**Comment by MichalMed** [comment]
Dobrý den, už je to opravené. Otestujte

**Comment by MichalMed** [comment]
Pracujete na dev verzi systému - tím pádem se tam občas může dostat něco, co nefunguje, jako například teď.

**Comment by xzbozink** [comment]
Dobrý den, otestováno na nově vytvořeném pracovním prostoru
https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/workspace/instance-946062713

Funguje jak očekáváno.
