### ISSUE TITLE
TermIt

### ISSUE THREAD

**Issue by tomas-prokes** [opendata-mvcr/sgov-assembly-line#90]
Dobrý den,
prosím o asistenci se správným nastavením práv k produkční verzi "Výrobní linky", resp. aplikace "TermIt".

Včera mi kolegyně Radka Domanská zpřístupnila "výrobní linku" a tak jsem si v ní dnes vytvořil nový "pracovní prostor" s názvem Facility Information Management a v něm i první slovník - legislativní slovník k vyhlášce č. 268/2009 Sb.

Po překliknutí do aplikace TermIt se ale v nabídce slovníku tento nový slovník nenabízí a místo toho vidím 17 jiných slovníků, které jsou spravovány v rámci jiného pracovního prostoru, konkrétně "Pracovního prostoru eGovernmentu". Nejsem tedy schopen ve 'svém' slovníku vytvářet a editovat pojmy.

Předem moc díky, 
Tomáš Prokeš

prokes@agentura-cas.cz
+ 420 727 833 559

**Comment by MichalMed** [comment]
řešeno v #91
